#!/bin/sh

[ "$ACTION" = ifup ] || [ "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate ] && [ -z "$IFUPDATE_ADDRESSES" ] && [ -z "$IFUPDATE_DATA" ] && exit 0

. /lib/functions/network.sh
network_flush_cache
network_find_wan6 NET_IF6

if [ "$INTERFACE" = "$NET_IF6" ]; then
  (
    LOCK_FILE="/tmp/lock/odhcpd_hotplug_lock"
    if [ -f "$LOCK_FILE" ]; then
      exit 1
    else
      echo $$ > "$LOCK_FILE" 2>/dev/null
      trap 'rm -f "$LOCK_FILE"' EXIT
      sleep 30
      [ -f '/etc/init.d/miniupnpd' ] && "/etc/init.d/miniupnpd" stop 2>&1
      "/sbin/ifup" lan 2>&1
      [ -f '/etc/init.d/miniupnpd' ] && "/etc/init.d/miniupnpd" start 2>&1
      sleep 10
      [ -f '/etc/init.d/odhcpd' ] && "/etc/init.d/odhcpd" reload 2>&1
      logger -t odhcpd "Reloading lan due to $ACTION of $INTERFACE ($DEVICE)"
    fi
  ) &
fi